version: '3.7'

services:

  web:
    build: .
    command: python /dashboard/manage.py runserver 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
    volumes:
      - .:/dashboard
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A dashboard worker -l info
    depends_on:
      - redis
      - beat
    volumes:
      - .:/dashboard

  beat:
    build: .
    command: celery -A dashboard beat -l info
    depends_on:
      - redis
      - db
    volumes:
      - .:/dashboard

  redis:
    image: bitnami/redis:5.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  redis_data:
    driver: local
