# Generated by Django 2.2.3 on 2019-07-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190726_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
