# Generated by Django 2.2.3 on 2019-07-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190726_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='story_url',
            field=models.URLField(null=True),
        ),
    ]
