# Generated by Django 2.2.3 on 2019-07-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190727_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
