# Generated by Django 2.2.3 on 2019-08-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_source_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
